### ISSUE TITLE
ch_datamod.md: missing information about * in sncbieaa

### ISSUE THREAD

**Issue by Artoria2e5** [ncbi/cxx-toolkit#345]
https://github.com/ncbi/cxx-toolkit/blob/gh-pages/pages/ch_datamod.md#genetic-codes currently has this to say about `sncbieaa`:

> Alphabet names are prefixed with "s" (e.g. sncbieaa) to indicate start codon arrays. Each cell of a start codon array contains either the gap code ("-" for ncbieaa) or an amino acid code if it is valid to use the codon as a start codon. Currently all starts are set to code for methionine, since it has never been convincingly demonstrated that a protein can start with any other amino acid. However, if other amino acids are shown to be used as starts, this structure can easily accommodate that information.

The issue here is that we have a three of new genetic codes relying on sncbieaa for sometimes-aa-sometimes-stop sort of codons in 27, 28, 31. The `ncbieaa` bit is an AA, and the only stop codons are found in `sncbieaa`.

**Comment by vakatov** [comment]
(I forwarded this question to the SeqArch team. Please stand by for the answer.)

**Comment by vakatov** [comment]
Done now: https://github.com/ncbi/cxx-toolkit/commit/cbbe419b05148c41208e6a398305e402ba4573b9
